spring:
  application:
    name: thrivex-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/thrive?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456
  freemarker:
    check-template-location: false

# JWT 配置
jwt:
  secret: bhmACjzWcsPzAi/pobbzByFjrJfm4Xe9ohZ4l2blLUo=
  expiration: 86400000  # 令牌有效期：24小时（单位：毫秒）

# MyBatis 配置
mybatis-plus:
  configuration:
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org:
      springframework:
        security: DEBUG
